# Numpy
Una biblioteca para operaciones matemáticas con elementos multidimesionales

## Variables

In [ ]:
import numpy as np

In [ ]:
a = np.array(5)

In [ ]:
v1 = np.array([-5, 2, 7, 1])

In [ ]:
m1 = np.array([[1, 4], [7, -2]])

In [ ]:
m2 = np.array([[-2, 11], [9, 5]])

## Operaciones

In [ ]:
# No ExE
res = v1**a
print(res)

[-3125    32 16807     1]


In [ ]:
# ExE
v2 = np.array([3, 4, -1, 0])
res2 = np.dot(v1, v2)
print(res2)

-14


In [ ]:
res3 = np.matmul(m1, m2)
res3

array([[ 34,  31],
       [-32,  67]])

## Cambios de dimensión

In [ ]:
a.shape

()

In [ ]:
v1.shape

(4,)

In [ ]:
m1.shape

(2, 2)

In [ ]:
a1 = a.reshape(1)
print(a1.shape)

(1,)


In [ ]:
a2 = a.reshape(1,1)
print(a2)

[[5]]


In [ ]:
m0 = m1.reshape(4)
print(m0)

[ 1  4  7 -2]
